trigger:
- none

pool:
  vmImage: ubuntu-latest
#  name: Default

stages:
  - stage:  tfdestroy
    jobs:
      - job: destroy
        steps:
          - task: TerraformInstaller@1
            displayName: install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'MSDN'
              backendAzureRmResourceGroupName: 'devops'
              backendAzureRmStorageAccountName: 'adomattglg'
              backendAzureRmContainerName: 'terraform'
              backendAzureRmKey: '$(Build.Repository.Name).tfstate'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              commandOptions: -destroy
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'MSDN'
          - task: TerraformTaskV4@4
            displayName: destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              environmentServiceNameAzureRM: 'MSDN'

